/**
 * ThemeManager - Manage application themes via CSS variables
 * Uses the exact same variable names as the original theme.js
 */

import { eventBus, Events } from '../core/EventBus.js';

// Theme definitions matching original theme.js
const themes = [
  {
    name: "Default",
    invertSettingsIcon: false,
    appBack: "#e0e0e0",
    buttonsBack: "#a74c00",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#d96200",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#d96200",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#a74c00",
    calDaysHoverBack: "#d96200",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#d96200",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#FF7A0D",
    calDaysHighlightedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#a74c00",
    calDOWText: "#000",
    calHeaderBack: "#ff7400",
    calHeaderBorder: "#ff7400",
    calHeaderDivider: "#ffb170",
    calHeaderHoverBack: "#d96200",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "none",
    foundBack: "#ffcda4",
    foundBorder: "lightgray",
    foundHoverBack: "#d96200",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#ff7400",
    notesBack: "#fff",
    notesBorder: "#ff7400",
    notesHeaderBack: "#ff7400",
    notesHeaderBorder: "#ff7400",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#ffcda4",
    pagesBack: "#fff",
    pagesBorder: "#ff7400",
    pageBack: "#ffcda4",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#d96200",
    pageHoverText: "#fff",
    pageSelectedBack: "#d96200",
    pageSelectedText: "#fff",
    pageSelectedBorder: "lightgray",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#ffcda4",
    settingsText: "#000",
    tabBack: "#a74c00",
    tabBorder: "#00ffea",
    tabDivider: "#ff7400",
    tabHoverBack: "#d96200",
    tabHoverText: "#fff",
    tabSelectedBack: "#ff7400",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#ffcda4",
    tasksBorder: "#ff7400",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#ffcda4",
    tvBorder: "lightgray",
    tvHoverBack: "#d96200",
    tvHoverText: "#fff",
    tvNavBack: "#a74c00",
    tvNavHover: "#d96200",
    tvSelectedBack: "#d96200",
    tvSelectedText: "#fff",
    tvText: "#000"
  },
  {
    name: "Warm",
    invertSettingsIcon: false,
    appBack: "#e0e0e0",
    buttonsBack: "#2D262C",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#536471",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#536471",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#2D262C",
    calDaysHoverBack: "#536471",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#536471",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#716053",
    calDaysHighlightedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#2D262C",
    calDOWText: "#000",
    calHeaderBack: "#CF5429",
    calHeaderBorder: "#CF5429",
    calHeaderDivider: "#DBA9A3",
    calHeaderHoverBack: "#536471",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "#fff",
    foundBack: "#B29294",
    foundBorder: "lightgray",
    foundHoverBack: "#536471",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#CF5429",
    notesBack: "#fff",
    notesBorder: "#CF5429",
    notesHeaderBack: "#CF5429",
    notesHeaderBorder: "#CF5429",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#B29294",
    pagesBack: "#fff",
    pagesBorder: "#CF5429",
    pageBack: "#B29294",
    pageBorder: "lightgray",
    pageText: "#fff",
    pageHoverBack: "#536471",
    pageHoverText: "#000",
    pageSelectedBack: "#536471",
    pageSelectedText: "#000",
    pageSelectedBorder: "lightgray",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#B29294",
    settingsText: "#000",
    tabBack: "#2D262C",
    tabBorder: "#000",
    tabDivider: "#2D262C",
    tabHoverBack: "#536471",
    tabHoverText: "#fff",
    tabSelectedBack: "#CF5429",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#B29294",
    tasksBorder: "#CF5429",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#B29294",
    tvBorder: "lightgray",
    tvHoverBack: "#536471",
    tvHoverText: "#fff",
    tvNavBack: "#2D262C",
    tvNavHover: "#536471",
    tvSelectedBack: "#536471",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "Cool",
    invertSettingsIcon: false,
    appBack: "#e0e0e0",
    buttonsBack: "#0D083B",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#5A5494",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#5A5494",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#0D083B",
    calDaysHoverBack: "#5A5494",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#5A5494",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#746EAD",
    calDaysHighlightedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#0D083B",
    calDOWText: "#000",
    calHeaderBack: "#383276",
    calHeaderBorder: "#383276",
    calHeaderDivider: "#5A5494",
    calHeaderHoverBack: "#5A5494",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "#fff",
    foundBack: "#837EB1",
    foundBorder: "lightgray",
    foundHoverBack: "#5A5494",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#383276",
    notesBack: "#fff",
    notesBorder: "#383276",
    notesHeaderBack: "#383276",
    notesHeaderBorder: "#383276",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#837EB1",
    pagesBack: "#fff",
    pagesBorder: "#383276",
    pageBack: "#837EB1",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#5A5494",
    pageHoverText: "#fff",
    pageSelectedBack: "#5A5494",
    pageSelectedText: "#fff",
    pageSelectedBorder: "lightgray",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#837EB1",
    settingsText: "#000",
    tabBack: "#0D083B",
    tabBorder: "#000",
    tabDivider: "#0D083B",
    tabHoverBack: "#5A5494",
    tabHoverText: "#fff",
    tabSelectedBack: "#383276",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#837EB1",
    tasksBorder: "#383276",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#837EB1",
    tvBorder: "lightgray",
    tvHoverBack: "#5A5494",
    tvHoverText: "#fff",
    tvNavBack: "#0D083B",
    tvNavHover: "#5A5494",
    tvSelectedBack: "#5A5494",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "Green",
    invertSettingsIcon: false,
    appBack: "#e0e0e0",
    buttonsBack: "#074600",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#1A6811",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#1A6811",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#074600",
    calDaysHoverBack: "#1A6811",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#1A6811",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#259418",
    calDaysHighlightedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#074600",
    calDOWText: "#000",
    calHeaderBack: "#2B8D21",
    calHeaderBorder: "#2B8D21",
    calHeaderDivider: "#5FAE57",
    calHeaderHoverBack: "#1A6811",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "#fff",
    foundBack: "#92D18B",
    foundBorder: "lightgray",
    foundHoverBack: "#1A6811",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#2B8D21",
    notesBack: "#fff",
    notesBorder: "#2B8D21",
    notesHeaderBack: "#2B8D21",
    notesHeaderBorder: "#2B8D21",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#92D18B",
    pagesBack: "#fff",
    pagesBorder: "#2B8D21",
    pageBack: "#92D18B",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#1A6811",
    pageHoverText: "#fff",
    pageSelectedBack: "#1A6811",
    pageSelectedText: "#fff",
    pageSelectedBorder: "lightgray",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#92D18B",
    settingsText: "#000",
    tabBack: "#074600",
    tabBorder: "#000",
    tabDivider: "#074600",
    tabHoverBack: "#1A6811",
    tabHoverText: "#fff",
    tabSelectedBack: "#2B8D21",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#92D18B",
    tasksBorder: "#2B8D21",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#92D18B",
    tvBorder: "lightgray",
    tvHoverBack: "#1A6811",
    tvHoverText: "#fff",
    tvNavBack: "#074600",
    tvNavHover: "#1A6811",
    tvSelectedBack: "#1A6811",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "Pink",
    invertSettingsIcon: false,
    appBack: "#e0e0e0",
    buttonsBack: "#6B1F17",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#9A392F",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#9A392F",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#6B1F17",
    calDaysHoverBack: "#9A392F",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#9A392F",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#C1473B",
    calDaysHighlightedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#6B1F17",
    calDOWText: "#000",
    calHeaderBack: "#BC2110",
    calHeaderBorder: "#BC2110",
    calHeaderDivider: "#F26A5C",
    calHeaderHoverBack: "#9A392F",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "#fff",
    foundBack: "#FF5E4D",
    foundBorder: "lightgray",
    foundHoverBack: "#9A392F",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#BC2110",
    notesBack: "#fff",
    notesBorder: "#BC2110",
    notesHeaderBack: "#BC2110",
    notesHeaderBorder: "#BC2110",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#FF5E4D",
    pagesBack: "#fff",
    pagesBorder: "#BC2110",
    pageBack: "#FF5E4D",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#9A392F",
    pageHoverText: "#fff",
    pageSelectedBack: "#9A392F",
    pageSelectedText: "#fff",
    pageSelectedBorder: "lightgray",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#FF5E4D",
    settingsText: "#000",
    tabBack: "#6B1F17",
    tabBorder: "#000",
    tabDivider: "#6B1F17",
    tabHoverBack: "#9A392F",
    tabHoverText: "#fff",
    tabSelectedBack: "#BC2110",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#FF5E4D",
    tasksBorder: "#BC2110",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#FF5E4D",
    tvBorder: "lightgray",
    tvHoverBack: "#9A392F",
    tvHoverText: "#fff",
    tvNavBack: "#6B1F17",
    tvNavHover: "#9A392F",
    tvSelectedBack: "#9A392F",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "Tron",
    invertSettingsIcon: true,
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "rgb(0, 255, 234)",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "rgb(0, 207, 190)",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "rgb(0, 207, 190)",
    buttonsSelectedText: "#000",
    buttonsText: "rgb(0, 255, 234)",
    calDaysBack: "#272727",
    calDaysBorder: "rgb(0, 255, 234)",
    calDaysHoverBack: "rgb(0, 207, 190)",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "#03FFEA",
    calDaysSelectedText: "#000",
    calDaysHighlightedBack: "#00CFBE",
    calDaysHighlightedText: "#000",
    calDaysText: "rgb(0, 255, 234)",
    calDOWBack: "#272727",
    calDOWBorder: "rgb(0, 255, 234)",
    calDOWText: "rgb(0, 255, 234)",
    calHeaderBack: "rgb(0, 255, 234)",
    calHeaderBorder: "rgb(0, 255, 234)",
    calHeaderDivider: "rgb(226, 255, 253)",
    calHeaderHoverBack: "rgb(0, 207, 190)",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "rgb(0, 255, 234)",
    foundBack: "rgb(173, 224, 220)",
    foundBorder: "lightgray",
    foundHoverBack: "rgb(0, 207, 190)",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "rgb(0, 255, 234)",
    notesBack: "#272727",
    notesBorder: "rgb(0, 255, 234)",
    notesHeaderBack: "rgb(0, 255, 234)",
    notesHeaderBorder: "rgb(0, 255, 234)",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "rgb(0, 255, 234)",
    notesHighlightText: "rgb(173, 224, 220)",
    pagesBack: "#272727",
    pagesBorder: "rgb(0, 255, 234)",
    pageBack: "#ade0dc",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "rgb(0, 207, 190)",
    pageHoverText: "#000",
    pageSelectedBack: "rgb(0, 207, 190)",
    pageSelectedText: "#000",
    pageSelectedBorder: "lightgray",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "rgb(0, 255, 234)",
    settingsBack: "rgb(173, 224, 220)",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#00ffea",
    tabDivider: "#00ffea",
    tabHoverBack: "rgb(0, 207, 190)",
    tabHoverText: "#272727",
    tabSelectedBack: "rgb(0, 255, 234)",
    tabSelectedText: "#272727",
    tabText: "rgb(0, 255, 234)",
    tasksBack: "rgb(173, 224, 220)",
    tasksBorder: "rgb(0, 255, 234)",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "rgb(0, 0, 0)",
    tvBack: "#ade0dc",
    tvBorder: "lightgray",
    tvHoverBack: "rgb(0, 207, 190)",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "rgb(0, 207, 190)",
    tvSelectedBack: "rgb(0, 207, 190)",
    tvSelectedText: "#000",
    tvText: "#000"
  },
  {
    name: "Clu",
    invertSettingsIcon: true,
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "#FFD93F",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "#FFE88D",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "#FFE88D",
    buttonsSelectedText: "#000",
    buttonsText: "#FFD93F",
    calDaysBack: "#272727",
    calDaysBorder: "#FFD93F",
    calDaysHoverBack: "#FFE88D",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "#FFE88D",
    calDaysSelectedText: "#000",
    calDaysHighlightedBack: "#FFDE5A",
    calDaysHighlightedText: "#fff",
    calDaysText: "#FFD93F",
    calDOWBack: "#272727",
    calDOWBorder: "#FFD93F",
    calDOWText: "#FFD93F",
    calHeaderBack: "#FFD93F",
    calHeaderBorder: "#FFD93F",
    calHeaderDivider: "#B89405",
    calHeaderHoverBack: "#FFE88D",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "#FFD93F",
    foundBack: "#F3C60C",
    foundBorder: "lightgray",
    foundHoverBack: "#FFE88D",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "#FFD93F",
    notesBack: "#272727",
    notesBorder: "#FFD93F",
    notesHeaderBack: "#FFD93F",
    notesHeaderBorder: "#FFD93F",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#FFD93F",
    notesHighlightText: "#F3C60C",
    pagesBack: "#272727",
    pagesBorder: "#FFD93F",
    pageBack: "#F3C60C",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#FFE88D",
    pageHoverText: "#000",
    pageSelectedBack: "#FFE88D",
    pageSelectedText: "#000",
    pageSelectedBorder: "lightgray",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "#FFD93F",
    settingsBack: "#F3C60C",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#FFD93F",
    tabDivider: "#FFD93F",
    tabHoverBack: "#FFE88D",
    tabHoverText: "#272727",
    tabSelectedBack: "#FFD93F",
    tabSelectedText: "#272727",
    tabText: "#FFD93F",
    tasksBack: "#F3C60C",
    tasksBorder: "#FFD93F",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#F3C60C",
    tvBorder: "lightgray",
    tvHoverBack: "#FFE88D",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "#FFE88D",
    tvSelectedBack: "#FFE88D",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "Metal",
    invertSettingsIcon: false,
    appBack: "#2b2b2b",
    buttonsBack: "#545454",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#6b6b6b",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#6b6b6b",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#2b2b2b",
    calDaysBorder: "#545454",
    calDaysHoverBack: "#6b6b6b",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#6b6b6b",
    calDaysSelectedText: "#fff",
    calDaysHighlightedBack: "#858585",
    calDaysHighlightedText: "#fff",
    calDaysText: "#fff",
    calDOWBack: "#2b2b2b",
    calDOWBorder: "#545454",
    calDOWText: "#fff",
    calHeaderBack: "#6b6b6b",
    calHeaderBorder: "#6b6b6b",
    calHeaderDivider: "#8c8c8c",
    calHeaderHoverBack: "#6b6b6b",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#2b2b2b",
    docBorder: "#6b6b6b",
    foundBack: "#4d4d4d",
    foundBorder: "lightgray",
    foundHoverBack: "#6b6b6b",
    foundHoverText: "#fff",
    foundText: "#fff",
    listBack: "#2b2b2b",
    listBorder: "#6b6b6b",
    notesBack: "#2b2b2b",
    notesBorder: "#6b6b6b",
    notesHeaderBack: "#6b6b6b",
    notesHeaderBorder: "#6b6b6b",
    notesHeaderText: "#fff",
    notesSelectedBack: "#00008b",
    notesSelectedText: "#fff",
    notesText: "#fff",
    notesHighlightText: "#4d4d4d",
    pagesBack: "#2b2b2b",
    pagesBorder: "#6b6b6b",
    pageBack: "#4d4d4d",
    pageBorder: "#4d4d4d",
    pageText: "#fff",
    pageHoverBack: "#6b6b6b",
    pageHoverText: "#fff",
    pageSelectedBack: "#6b6b6b",
    pageSelectedText: "#fff",
    pageSelectedBorder: "#fff",
    searchBack: "#2b2b2b",
    searchBorder: "lightgray",
    searchText: "#fff",
    settingsBack: "#4d4d4d",
    settingsText: "#fff",
    tabBack: "#545454",
    tabBorder: "#00ffea",
    tabDivider: "#6b6b6b",
    tabHoverBack: "#6b6b6b",
    tabHoverText: "#fff",
    tabSelectedBack: "#6b6b6b",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#4d4d4d",
    tasksBorder: "#6b6b6b",
    tasksSelectedBack: "#00008b",
    tasksSelectedText: "#fff",
    tasksText: "#fff",
    tvBack: "#4d4d4d",
    tvBorder: "lightgray",
    tvHoverBack: "#6b6b6b",
    tvHoverText: "#fff",
    tvNavBack: "#000",
    tvNavHover: "#fff",
    tvSelectedBack: "#6b6b6b",
    tvSelectedText: "#fff",
    tvText: "#fff"
  },
  {
    name: "OrangeWave",
    invertSettingsIcon: true,
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "#FFA726",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "#FFB74D",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "#FFB74D",
    buttonsSelectedText: "#000",
    buttonsText: "#FFA726",
    calDaysBack: "#272727",
    calDaysBorder: "#FFA726",
    calDaysHoverBack: "#FFB74D",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "#FFB74D",
    calDaysSelectedText: "#000",
    calDaysHighlightedBack: "#FFA21A",
    calDaysHighlightedText: "#000",
    calDaysText: "#FFA726",
    calDOWBack: "#272727",
    calDOWBorder: "#FFA726",
    calDOWText: "#FFA726",
    calHeaderBack: "#FFA726",
    calHeaderBorder: "#FFA726",
    calHeaderDivider: "#FFE082",
    calHeaderHoverBack: "#FFB74D",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "#FFA726",
    foundBack: "#FFE0B2",
    foundBorder: "lightgray",
    foundHoverBack: "#FFB74D",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "#FFA726",
    notesBack: "#272727",
    notesBorder: "#FFA726",
    notesHeaderBack: "#FFA726",
    notesHeaderBorder: "#FFA726",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#FFA726",
    notesHighlightText: "#FFE0B2",
    pagesBack: "#272727",
    pagesBorder: "#FFA726",
    pageBack: "#FFE0B2",
    pageBorder: "lightgray",
    pageText: "#000",
    pageHoverBack: "#FFB74D",
    pageHoverText: "#000",
    pageSelectedBack: "#FFB74D",
    pageSelectedText: "#000",
    pageSelectedBorder: "lightgray",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "#FFA726",
    settingsBack: "#FFE0B2",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#FFA726",
    tabDivider: "#FFA726",
    tabHoverBack: "#FFB74D",
    tabHoverText: "#272727",
    tabSelectedBack: "#FFB74D",
    tabSelectedText: "#272727",
    tabText: "#FFA726",
    tasksBack: "#FFE0B2",
    tasksBorder: "#FFA726",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#272727",
    tvBack: "#FFE0B2",
    tvBorder: "lightgray",
    tvHoverBack: "#FFB74D",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "#FFB74D",
    tvSelectedBack: "#FFB74D",
    tvSelectedText: "#fff",
    tvText: "#fff"
  }
];

// All CSS variable names that themes can set
const themeProperties = [
  'appBack', 'buttonsBack', 'buttonsBorder', 'buttonsBorderStyle', 'buttonsBorderSize',
  'buttonsHoverBack', 'buttonsHoverText', 'buttonsSelectedBack', 'buttonsSelectedText', 'buttonsText',
  'calDaysBack', 'calDaysBorder', 'calDaysHoverBack', 'calDaysHoverText',
  'calDaysSelectedBack', 'calDaysSelectedText', 'calDaysHighlightedBack', 'calDaysHighlightedText', 'calDaysText',
  'calDOWBack', 'calDOWBorder', 'calDOWText',
  'calHeaderBack', 'calHeaderBorder', 'calHeaderDivider', 'calHeaderHoverBack', 'calHeaderHoverText', 'calHeaderText',
  'docBack', 'docBorder',
  'foundBack', 'foundBorder', 'foundHoverBack', 'foundHoverText', 'foundText',
  'listBack', 'listBorder',
  'notesBack', 'notesBorder', 'notesHeaderBack', 'notesHeaderBorder', 'notesHeaderText',
  'notesSelectedBack', 'notesSelectedText', 'notesText', 'notesHighlightText',
  'pagesBack', 'pagesBorder', 'pageBack', 'pageBorder', 'pageText',
  'pageHoverBack', 'pageHoverText', 'pageSelectedBack', 'pageSelectedText', 'pageSelectedBorder',
  'searchBack', 'searchBorder', 'searchText',
  'settingsBack', 'settingsText',
  'tabBack', 'tabBorder', 'tabDivider', 'tabHoverBack', 'tabHoverText', 'tabSelectedBack', 'tabSelectedText', 'tabText',
  'tasksBack', 'tasksBorder', 'tasksSelectedBack', 'tasksSelectedText', 'tasksText',
  'tvBack', 'tvBorder', 'tvHoverBack', 'tvHoverText', 'tvNavBack', 'tvNavHover', 'tvSelectedBack', 'tvSelectedText', 'tvText'
];

export class ThemeManager {
  constructor() {
    this.currentThemeIndex = 0;
  }

  /**
   * Get all available themes
   * @returns {Array<{name: string, invertSettingsIcon: boolean}>}
   */
  getThemes() {
    return themes.map(t => ({
      name: t.name,
      invertSettingsIcon: t.invertSettingsIcon
    }));
  }

  /**
   * Get the current theme index
   * @returns {number}
   */
  getCurrentThemeIndex() {
    return this.currentThemeIndex;
  }

  /**
   * Get the current theme
   * @returns {Object}
   */
  getCurrentTheme() {
    return themes[this.currentThemeIndex];
  }

  /**
   * Set the theme by index
   * @param {number} index - Theme index
   */
  setTheme(index) {
    if (index < 0 || index >= themes.length) {
      index = 0;
    }

    this.currentThemeIndex = index;
    const theme = themes[index];
    const d = document.documentElement.style;

    // Apply all theme properties as CSS variables
    themeProperties.forEach(prop => {
      if (theme[prop] !== undefined) {
        d.setProperty(`--${prop}`, theme[prop]);
      }
    });

    // Set special classes for inverted themes
    document.body.classList.toggle('theme-inverted', theme.invertSettingsIcon);

    eventBus.emit(Events.THEME_CHANGED, {
      themeIndex: index,
      theme: theme.name,
      invertSettingsIcon: theme.invertSettingsIcon
    });
  }

  /**
   * Cycle to the next theme
   * @returns {number} New theme index
   */
  nextTheme() {
    const newIndex = (this.currentThemeIndex + 1) % themes.length;
    this.setTheme(newIndex);
    return newIndex;
  }

  /**
   * Get theme count
   * @returns {number}
   */
  getThemeCount() {
    return themes.length;
  }

  /**
   * Get theme by index
   * @param {number} index - Theme index
   * @returns {Object|null}
   */
  getTheme(index) {
    return themes[index] || null;
  }

  /**
   * Check if current theme inverts the settings icon (uses black instead of white)
   * @returns {boolean}
   */
  usesInvertedIcons() {
    return themes[this.currentThemeIndex]?.invertSettingsIcon || false;
  }
}

// Export singleton instance
export const themeManager = new ThemeManager();
