// #region THEMES
var themeWarm = {
  name: "Warm",
  invertSettingsIcon: "false",
  appBack: "#e0e0e0",
  buttonsBack: "#2D262C",
  buttonsBorder: "#fff",
  buttonsBorderStyle: "none",
  buttonsBorderSize: "0px",
  buttonsHoverBack: "#536471",
  buttonsHoverText: "#fff",
  buttonsSelectedBack: "#536471",
  buttonsSelectedText: "#fff",
  buttonsText: "#fff",
  calDaysBack: "#fff",
  calDaysBorder: "#2D262C",
  calDaysHoverBack: "#536471",
  calDaysHoverText: "#fff",
  calDaysSelectedBack: "#536471",
  calDaysSelectedText: "#fff",
  calDaysText: "#000",
  calDOWBack: "#fff",
  calDOWBorder: "#2D262C",
  calDOWText: "#000",
  calHeaderBack: "#CF5429",
  calHeaderBorder: "#CF5429",
  calHeaderDivider: "#DBA9A3",
  calHeaderHoverBack: "#536471",
  calHeaderHoverText: "#fff",
  calHeaderText: "#fff",
  docBack: "#e0e0e0",
  docBorder: "#fff",
  foundBack: "#B29294",
  foundBorder: "lightgray",
  foundHoverBack: "#536471",
  foundHoverText: "#fff",
  foundText: "#000",
  listBack: "#fff",
  listBorder: "#CF5429",
  notesBack: "#fff",
  notesBorder: "#CF5429",
  notesHeaderBack: "#CF5429",
  notesHeaderBorder: "#CF5429",
  notesHeaderText: "#fff",
  notesSelectedBack: "blue",
  notesSelectedText: "#000",
  notesText: "#000",
  notesHighlightText: "#B29294",
  pagesBack: "#fff",
  pagesBorder: "#CF5429",
  pageBack: "#B29294",
  pageBorder: "lightgray",
  pageText: "#000",
  searchBack: "#fff",
  searchBorder: "lightgray",
  searchText: "#000",
  settingsBack: "#B29294",
  settingsText: "#000",
  tabBack: "#2D262C",
  tabBorder: "#000",
  tabDivider: "#2D262C",
  tabHoverBack: "#536471",
  tabHoverText: "#fff",
  tabSelectedBack: "#CF5429",
  tabSelectedText: "#fff",
  tabText: "#fff",
  tasksBack: "#B29294",
  tasksBorder: "#CF5429",
  tasksSelectedBack: "blue",
  tasksSelectedText: "#000",
  tasksText: "#000",
  tvBack: "#B29294",
  tvBorder: "lightgray",
  tvHoverBack: "#536471",
  tvHoverText: "#fff",
  tvNavBack: "#2D262C",
  tvNavHover: "#536471",
  tvSelectedBack: "#536471",
  tvSelectedText: "#fff",
  tvText: "#fff"
};
  
  var themeCool = {
    name: “Cool”,
    invertSettingsIcon: "false",
    appBack: "#e0e0e0",
    buttonsBack: "#0D083B",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#5A5494",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#5A5494",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#0D083B",
    calDaysHoverBack: "#5A5494",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#5A5494",
    calDaysSelectedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#0D083B",
    calDOWText: "#000",
    calHeaderBack: "#383276",
    calHeaderBorder: "#383276",
    calHeaderDivider: "#5A5494",
    calHeaderHoverBack: "#5A5494",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "#fff",
    foundBack: "#837EB1",
    foundBorder: "lightgray",
    foundHoverBack: "#5A5494",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#383276",
    notesBack: "#fff",
    notesBorder: "#383276",
    notesHeaderBack: "#383276",
    notesHeaderBorder: "#383276",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#837EB1",
    pagesBack: "#fff",
    pagesBorder: "#383276",
    pageBack: "#837EB1",
    pageBorder: "lightgray",
    pageText: "#000",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#837EB1",
    settingsText: "#000",
    tabBack: "#0D083B",
    tabBorder: "#000",
    tabDivider: "#0D083B",
    tabHoverBack: "#5A5494",
    tabHoverText: "#fff",
    tabSelectedBack: "#383276",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#837EB1",
    tasksBorder: "#383276",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#837EB1",
    tvBorder: "lightgray",
    tvHoverBack: "#5A5494",
    tvHoverText: "#fff",
    tvNavBack: "#0D083B",
    tvNavHover: "#5A5494",
    tvSelectedBack: "#5A5494",
    tvSelectedText: "#fff",
    tvText: "#fff"
  };
  
  var themeGreen = {
    name: "Green",
    buttonface: "#074600",
    buttontext: "#fff",
    buttonbordersize: "0px",
    buttonborder: "none",
    buttonbordercolor: "#fff",
    buttonhover: "#1A6811",
    buttonhovertext: "#fff",
    titlebar: "#2B8D21",
    titletext: "#fff",
    compColor1: "#5FAE57",
    compColor2: "#92D18B",
    notesBGColor: "#fff",
    notesTextColor: "#000",
    bodyColor: "#e0e0e0",
    invertSettingsIcon: "false",
    calBorder: "#074600"
  };
  
  var themePink = {
    name: "Pink",
    buttonface: "#6B1F17",
    buttontext: "#fff",
    buttonbordersize: "0px",
    buttonborder: "none",
    buttonbordercolor: "#fff",
    buttonhover: "#9A392F",
    buttonhovertext: "#fff",
    titlebar: "#BC2110",
    titletext: "#fff",
    compColor1: "#F26A5C",
    compColor2: "#FF5E4D",
    notesBGColor: "#fff",
    notesTextColor: "#000",
    bodyColor: "#e0e0e0",
    invertSettingsIcon: "false",
    calBorder: "#6B1F17"
  };
  
  var themeDefault = {
    name: "Default",
    invertSettingsIcon: "false",
    appBack: "#e0e0e0",
    buttonsBack: "#a74c00",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#d96200",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#d96200",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#fff",
    calDaysBorder: "#a74c00",
    calDaysHoverBack: "#d96200",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#d96200",
    calDaysSelectedText: "#fff",
    calDaysText: "#000",
    calDOWBack: "#fff",
    calDOWBorder: "#a74c00",
    calDOWText: "#000",
    calHeaderBack: "#ff7400",
    calHeaderBorder: "#ff7400",
    calHeaderDivider: "#ffb170",
    calHeaderHoverBack: "#d96200",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#e0e0e0",
    docBorder: "none",
    foundBack: "#ffcda4",
    foundBorder: "lightgray",
    foundHoverBack: "#d96200",
    foundHoverText: "#fff",
    foundText: "#000",
    listBack: "#fff",
    listBorder: "#ff7400",
    notesBack: "#fff",
    notesBorder: "#ff7400",
    notesHeaderBack: "#ff7400",
    notesHeaderBorder: "#ff7400",
    notesHeaderText: "#fff",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#000",
    notesHighlightText: "#ffcda4",
    pagesBack: "#fff",
    pagesBorder: "#ff7400",
    pageBack: "#ffcda4",
    pageBorder: "lightgray",
    pageText: "#000",
    searchBack: "#fff",
    searchBorder: "lightgray",
    searchText: "#000",
    settingsBack: "#ffcda4",
    settingsText: "#000",
    tabBack: "#a74c00",
    tabBorder: "#00ffea",
    tabDivider: "#ff7400",
    tabHoverBack: "#d96200",
    tabHoverText: "#fff",
    tabSelectedBack: "#ff7400",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#ffcda4",
    tasksBorder: "#ff7400",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#000",
    tvBack: "#ffcda4",
    tvBorder: "lightgray",
    tvHoverBack: "#d96200",
    tvHoverText: "#fff",
    tvNavBack: "#a74c00",
    tvNavHover: "#d96200",
    tvSelectedBack: "#d96200",
    tvSelectedText: "#fff",
    tvText: "#fff"
  };
  
  var themeTron = {
    name: "Tron",
    invertSettingsIcon: "true",
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "rgb(0, 255, 234)",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "rgb(0, 207, 190)",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "rgb(0, 207, 190)",
    buttonsSelectedText: "#000",
    buttonsText: "Rgb(0, 255, 234)",
    calDaysBack: "#272727",
    calDaysBorder: "rgb(0, 255, 234)",
    calDaysHoverBack: "rgb(0, 207, 190)",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "rgb(0, 207, 190)",
    calDaysSelectedText: "#000",
    calDaysText: "rgb(0, 255, 234)",
    calDOWBack: "#272727",
    calDOWBorder: "rgb(0, 255, 234)",
    calDOWText: "rgb(0, 255, 234)",
    calHeaderBack: "rgb(0, 255, 234)",
    calHeaderBorder: "rgb(0, 255, 234)",
    calHeaderDivider: "rgb(226, 255, 253)",
    calHeaderHoverBack: "rgb(0, 207, 190)",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "rgb(0, 255, 234)",
    foundBack: "rgb(173, 224, 220)",
    foundBorder: "lightgray",
    foundHoverBack: "rgb(0, 207, 190)",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "rgb(0, 255, 234)",
    notesBack: "#272727",
    notesBorder: "rgb(0, 255, 234)",
    notesHeaderBack: "rgb(0, 255, 234)",
    notesHeaderBorder: "rgb(0, 255, 234)",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "rgb(0, 255, 234)",
    notesHighlightText: "rgb(173, 224, 220)",
    pagesBack: "#272727",
    pagesBorder: "rgb(0, 255, 234)",
    pageBack: "#ade0dc",
    pageBorder: "lightgray",
    pageText: "#000",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "rgb(0, 255, 234)",
    settingsBack: "rgb(173, 224, 220)",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#00ffea",
    tabDivider: "#00ffea",
    tabHoverBack: "rgb(0, 207, 190)",
    tabHoverText: "#272727",
    tabSelectedBack: "rgb(0, 255, 234)",
    tabSelectedText: "#272727",
    tabText: "Rgb(0, 255, 234)",
    tasksBack: "rgb(173, 224, 220)",
    tasksBorder: "rgb(0, 255, 234)",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "rgb(0, 255, 234)",
    tvBack: "#ade0dc",
    tvBorder: "lightgray",
    tvHoverBack: "rgb(0, 207, 190)",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "rgb(0, 207, 190)",
    tvSelectedBack: "rgb(0, 207, 190)",
    tvSelectedText: "#fff",
    tvText: "#fff"
  };

  var themeOrangeWave = {
    name: "OrangeWave",
    invertSettingsIcon: "true",
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "#FFA726",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "#FFB74D",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "#FFB74D",
    buttonsSelectedText: "#000",
    buttonsText: "#FFA726",
    calDaysBack: "#272727",
    calDaysBorder: "#FFA726",
    calDaysHoverBack: "#FFB74D",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "#FFB74D",
    calDaysSelectedText: "#000",
    calDaysText: "#FFA726",
    calDOWBack: "#272727",
    calDOWBorder: "#FFA726",
    calDOWText: "#FFA726",
    calHeaderBack: "#FFA726",
    calHeaderBorder: "#FFA726",
    calHeaderDivider: "#FFE082",
    calHeaderHoverBack: "#FFB74D",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "#FFA726",
    foundBack: "#FFE0B2",
    foundBorder: "lightgray",
    foundHoverBack: "#FFB74D",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "#FFA726",
    notesBack: "#272727",
    notesBorder: "#FFA726",
    notesHeaderBack: "#FFA726",
    notesHeaderBorder: "#FFA726",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#FFA726",
    notesHighlightText: "#FFE0B2",
    pagesBack: "#272727",
    pagesBorder: "#FFA726",
    pageBack: "#FFE0B2",
    pageBorder: "lightgray",
    pageText: "#000",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "#FFA726",
    settingsBack: "#FFE0B2",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#FFA726",
    tabDivider: "#FFA726",
    tabHoverBack: "#FFB74D",
    tabHoverText: "#272727",
    tabSelectedBack: "#FFB74D",
    tabSelectedText: "#272727",
    tabText: "#FFA726",
    tasksBack: "#FFE0B2",
    tasksBorder: "#FFA726",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#FFA726",
    tvBack: "#FFE0B2",
    tvBorder: "lightgray",
    tvHoverBack: "#FFB74D",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "#FFB74D",
    tvSelectedBack: "#FFB74D",
    tvSelectedText: "#fff",
    tvText: "#fff"
};
  
  var themeClu = {
    name: "Clu",
    invertSettingsIcon: "true",
    appBack: "#272727",
    buttonsBack: "#272727",
    buttonsBorder: "#FFD93F",
    buttonsBorderStyle: "solid",
    buttonsBorderSize: "1px",
    buttonsHoverBack: "#FFE88D",
    buttonsHoverText: "#000",
    buttonsSelectedBack: "#FFE88D",
    buttonsSelectedText: "#000",
    buttonsText: "#FFD93F",
    calDaysBack: "#272727",
    calDaysBorder: "#FFD93F",
    calDaysHoverBack: "#FFE88D",
    calDaysHoverText: "#000",
    calDaysSelectedBack: "#FFE88D",
    calDaysSelectedText: "#000",
    calDaysText: "#FFD93F",
    calDOWBack: "#272727",
    calDOWBorder: "#FFD93F",
    calDOWText: "#FFD93F",
    calHeaderBack: "#FFD93F",
    calHeaderBorder: "#FFD93F",
    calHeaderDivider: "#B89405",
    calHeaderHoverBack: "#FFE88D",
    calHeaderHoverText: "#272727",
    calHeaderText: "#272727",
    docBack: "#272727",
    docBorder: "#FFD93F",
    foundBack: "#F3C60C",
    foundBorder: "lightgray",
    foundHoverBack: "#FFE88D",
    foundHoverText: "#000",
    foundText: "#000",
    listBack: "#272727",
    listBorder: "#FFD93F",
    notesBack: "#272727",
    notesBorder: "#FFD93F",
    notesHeaderBack: "#FFD93F",
    notesHeaderBorder: "#FFD93F",
    notesHeaderText: "#272727",
    notesSelectedBack: "blue",
    notesSelectedText: "#000",
    notesText: "#FFD93F",
    notesHighlightText: "#F3C60C",
    pagesBack: "#272727",
    pagesBorder: "#FFD93F",
    pageBack: "#F3C60C",
    pageBorder: "lightgray",
    pageText: "#000",
    searchBack: "#272727",
    searchBorder: "lightgray",
    searchText: "#FFD93F",
    settingsBack: "#F3C60C",
    settingsText: "#000",
    tabBack: "#272727",
    tabBorder: "#FFD93F",
    tabDivider: "#FFD93F",
    tabHoverBack: "#FFE88D",
    tabHoverText: "#272727",
    tabSelectedBack: "#FFD93F",
    tabSelectedText: "#272727",
    tabText: "#FFD93F",
    tasksBack: "#F3C60C",
    tasksBorder: "#FFD93F",
    tasksSelectedBack: "blue",
    tasksSelectedText: "#000",
    tasksText: "#FFD93F",
    tvBack: "#F3C60C",
    tvBorder: "lightgray",
    tvHoverBack: "#FFE88D",
    tvHoverText: "#000",
    tvNavBack: "#272727",
    tvNavHover: "#FFE88D",
    tvSelectedBack: "#FFE88D",
    tvSelectedText: "#fff",
    tvText: "#fff"
  };
  
  var themeMetal = {
    name: "Metal",
    invertSettingsIcon: "false",
    appBack: "#2b2b2b",
    buttonsBack: "#545454",
    buttonsBorder: "#fff",
    buttonsBorderStyle: "none",
    buttonsBorderSize: "0px",
    buttonsHoverBack: "#6b6b6b",
    buttonsHoverText: "#fff",
    buttonsSelectedBack: "#6b6b6b",
    buttonsSelectedText: "#fff",
    buttonsText: "#fff",
    calDaysBack: "#2b2b2b",
    calDaysBorder: "#545454",
    calDaysHoverBack: "#6b6b6b",
    calDaysHoverText: "#fff",
    calDaysSelectedBack: "#6b6b6b",
    calDaysSelectedText: "#fff",
    calDaysText: "#fff",
    calDOWBack: "#2b2b2b",
    calDOWBorder: "#545454",
    calDOWText: "#fff",
    calHeaderBack: "#6b6b6b",
    calHeaderBorder: "#6b6b6b",
    calHeaderDivider: "#8c8c8c",
    calHeaderHoverBack: "#6b6b6b",
    calHeaderHoverText: "#fff",
    calHeaderText: "#fff",
    docBack: "#2b2b2b",
    docBorder: "none",
    foundBack: "#4d4d4d",
    foundBorder: "lightgray",
    foundHoverBack: "#6b6b6b",
    foundHoverText: "#fff",
    foundText: "#fff",
    listBack: "#2b2b2b",
    listBorder: "#6b6b6b",
    notesBack: "#2b2b2b",
    notesBorder: "#6b6b6b",
    notesHeaderBack: "#6b6b6b",
    notesHeaderBorder: "#6b6b6b",
    notesHeaderText: "#fff",
    notesSelectedBack: "#00008b",
    notesSelectedText: "#fff",
    notesText: "#fff",
    notesHighlightText: "#4d4d4d",
    pagesBack: "#2b2b2b",
    pagesBorder: "#6b6b6b",
    pageBack: "#4d4d4d",
    pageBorder: "lightgray",
    pageText: "#fff",
    searchBack: "#2b2b2b",
    searchBorder: "lightgray",
    searchText: "#fff",
    settingsBack: "#4d4d4d",
    settingsText: "#fff",
    tabBack: "#545454",
    tabBorder: "#00ffea",
    tabDivider: "#6b6b6b",
    tabHoverBack: "#6b6b6b",
    tabHoverText: "#fff",
    tabSelectedBack: "#6b6b6b",
    tabSelectedText: "#fff",
    tabText: "#fff",
    tasksBack: "#4d4d4d",
    tasksBorder: "#6b6b6b",
    tasksSelectedBack: "#00008b",
    tasksSelectedText: "#fff",
    tasksText: "#fff",
    tvBack: "#4d4d4d",
    tvBorder: "lightgray",
    tvHoverBack: "#6b6b6b",
    tvHoverText: "#fff",
    tvNavBack: "#545454",
    tvNavHover: "#6b6b6b",
    tvSelectedBack: "#6b6b6b",
    tvSelectedText: "#fff",
    tvText: "#fff"
};


  var themes = [
    themeDefault,
    themeWarm,
    themeCool,
    themeGreen,
    themePink,
    themeTron,
    themeClu,
    themeMetal,
    themeOrangeWave,
  ];

  var selectedTheme = 0;
  
  function changeTheme(themeIndex, callback) {
    console.log("changeTheme called, themeIndex = " + themeIndex);
    var d = document.documentElement.style;
    d.setProperty("--appBack", themes[themeIndex].appBack);
    d.setProperty("--buttonsBack", themes[themeIndex].buttonsBack);
    d.setProperty("--buttonsBorder", themes[themeIndex].buttonsBorder);
    d.setProperty("--buttonsBorderStyle", themes[themeIndex].buttonsBorderStyle);
    d.setProperty("--buttonsBorderSize", themes[themeIndex].buttonsBorderSize);
    d.setProperty("--buttonsHoverBack", themes[themeIndex].buttonsHoverBack);
    d.setProperty("--buttonsHoverText", themes[themeIndex].buttonsHoverText);
    d.setProperty("--buttonsSelectedBack", themes[themeIndex].buttonsSelectedBack);
    d.setProperty("--buttonsSelectedText", themes[themeIndex].buttonsSelectedText);
    d.setProperty("--buttonsText", themes[themeIndex].buttonsText);
    d.setProperty("--calDaysBack", themes[themeIndex].calDaysBack);
    d.setProperty("--calDaysBorder", themes[themeIndex].calDaysBorder);
    d.setProperty("--calDaysHoverBack", themes[themeIndex].calDaysHoverBack);
    d.setProperty("--calDaysHoverText", themes[themeIndex].calDaysHoverText);
    d.setProperty("--calDaysSelectedBack", themes[themeIndex].calDaysSelectedBack);
    d.setProperty("--calDaysSelectedText", themes[themeIndex].calDaysSelectedText);
    d.setProperty("--calDaysText", themes[themeIndex].calDaysText);
    d.setProperty("--calDOWBack", themes[themeIndex].calDOWBack);
    d.setProperty("--calDOWBorder", themes[themeIndex].calDOWBorder);
    d.setProperty("--calDOWText", themes[themeIndex].calDOWText);
    d.setProperty("--calHeaderBack", themes[themeIndex].calHeaderBack);
    d.setProperty("--calHeaderBorder", themes[themeIndex].calHeaderBorder);
    d.setProperty("--calHeaderDivider", themes[themeIndex].calHeaderDivider);
    d.setProperty("--calHeaderHoverBack", themes[themeIndex].calHeaderHoverBack);
    d.setProperty("--calHeaderHoverText", themes[themeIndex].calHeaderHoverText);
    d.setProperty("--calHeaderText", themes[themeIndex].calHeaderText);
    d.setProperty("--docBack", themes[themeIndex].docBack);
    d.setProperty("--docBorder", themes[themeIndex].docBorder);
    d.setProperty("--foundBack", themes[themeIndex].foundBack);
    d.setProperty("--foundBorder", themes[themeIndex].foundBorder);
    d.setProperty("--foundHoverBack", themes[themeIndex].foundHoverBack);
    d.setProperty("--foundHoverText", themes[themeIndex].foundHoverText);
    d.setProperty("--foundText", themes[themeIndex].foundText);
    d.setProperty("--listBack", themes[themeIndex].listBack);
    d.setProperty("--listBorder", themes[themeIndex].listBorder);
    d.setProperty("--notesBack", themes[themeIndex].notesBack);
    d.setProperty("--notesBorder", themes[themeIndex].notesBorder);
    d.setProperty("--notesHeaderBack", themes[themeIndex].notesHeaderBack);
    d.setProperty("--notesHeaderBorder", themes[themeIndex].notesHeaderBorder);
    d.setProperty("--notesHeaderText", themes[themeIndex].notesHeaderText);
    d.setProperty("--notesSelectedBack", themes[themeIndex].notesSelectedBack);
    d.setProperty("--notesSelectedText", themes[themeIndex].notesSelectedText);
    d.setProperty("--notesText", themes[themeIndex].notesText);
    d.setProperty("--notesHighlightText", themes[themeIndex].notesHighlightText);
    d.setProperty("--pagesBack", themes[themeIndex].pagesBack);
    d.setProperty("--pagesBorder", themes[themeIndex].pagesBorder);
    d.setProperty("--pageBack", themes[themeIndex].pageBack);
    d.setProperty("--pageBorder", themes[themeIndex].pageBorder);
    d.setProperty("--pageText", themes[themeIndex].pageText);
    d.setProperty("--searchBack", themes[themeIndex].searchBack);
    d.setProperty("--searchBorder", themes[themeIndex].searchBorder);
    d.setProperty("--searchText", themes[themeIndex].searchText);
    d.setProperty("--settingsBack", themes[themeIndex].settingsBack);
    d.setProperty("--settingsText", themes[themeIndex].settingsText);
    d.setProperty("--tabBack", themes[themeIndex].tabBack);
    d.setProperty("--tabBorder", themes[themeIndex].tabBorder);
    d.setProperty("--tabDivider", themes[themeIndex].tabDivider);
    d.setProperty("--tabHoverBack", themes[themeIndex].tabHoverBack);
    d.setProperty("--tabHoverText", themes[themeIndex].tabHoverText);
    d.setProperty("--tabSelectedBack", themes[themeIndex].tabSelectedBack);
    d.setProperty("--tabSelectedText", themes[themeIndex].tabSelectedText);
    d.setProperty("--tabText", themes[themeIndex].tabText);
    d.setProperty("--tasksBack", themes[themeIndex].tasksBack);
    d.setProperty("--tasksBorder", themes[themeIndex].tasksBorder);
    d.setProperty("--tasksSelectedBack", themes[themeIndex].tasksSelectedBack);
    d.setProperty("--tasksSelectedText", themes[themeIndex].tasksSelectedText);
    d.setProperty("--tasksText", themes[themeIndex].tasksText);
    d.setProperty("--tvBack", themes[themeIndex].tvBack);
    d.setProperty("--tvBorder", themes[themeIndex].tvBorder);
    d.setProperty("--tvHoverBack", themes[themeIndex].tvHoverBack);
    d.setProperty("--tvHoverText", themes[themeIndex].tvHoverText);
    d.setProperty("--tvNavBack", themes[themeIndex].tvNavBack);
    d.setProperty("--tvNavHover", themes[themeIndex].tvNavHover);
    d.setProperty("--tvSelectedBack", themes[themeIndex].tvSelectedBack);
    d.setProperty("--tvSelectedText", themes[themeIndex].tvSelectedText);
    d.setProperty("--tvText", themes[themeIndex].tvText);
    selectedTheme = themeIndex;
    if (callback) callback();
  }
  